[package]
edition = "2021"
name = "cryptopals_rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7"
base64 = "0.13"
block-modes = "0.8"
block-padding = "0.3"
hex = "0.4"
rand = "0.8"
